version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    networks:
      - ecommerce-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "5002"
    deploy:
      replicas: 3 # Number of instances
      restart_policy:
        condition: on-failure
    environment:
      - FLASK_ENV=production
    networks:
      - ecommerce-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "5003:5003"
    networks:
      - ecommerce-network

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "5004:5004"
    networks:
       - ecommerce-network


networks:
  ecommerce-network:
    driver: bridge
