swagger: "2.0"
info:
  title: "User Service API"
  description: "API for user registration and authentication"
  version: "1.0.0"
host: "localhost:5001"
schemes:
  - "http"
paths:
  /register:
    post:
      summary: "Register a new user"
      description: "Endpoint to register a new user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"

