swagger: "2.0"
info:
  title: "Payment Service API"
  description: "API for user registration and authentication"
  version: "1.0.0"
host: "localhost:5004"
schemes:
  - "http"
paths:
  /register:
    post:
      summary: "Payment Service for User"
      description: "user payment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "User registered successfully"
